services:
  login:
    build:
      context: .
      dockerfile: Dockerfile
      target: login_service
    ports:
      - "5001:5000"
  minio:
    build:
      context: .
      dockerfile: Dockerfile
      target: minio_service
    ports:
      - "5002:5000"
  purchase:
    build:
      context: .
      dockerfile: Dockerfile
      target: purchase_service
    ports:
      - "5003:5000"
  minio-deployment:
    build:
      context: .
      dockerfile: Dockerfile
      target: minio-deployment_service
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio
